version: '3.3'
services:
  db:
    image: mysql:8.0.33
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'crud'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'my-secret-pw'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      - '3306:3306'

volumes:
  crud: